### ISSUE TITLE
Make --max_processes argument in write_xdlrc optional parameter

### ISSUE THREAD

**Issue by trharoldsen** [bradselw/tincr#46]
It looks like the argument is currently required.  Could we make it optional with a default value of 1.  If a user wants to use more than 1 process, allowing the user to specify more if desired.

**Comment by bradselw** [comment]
The `--max_processes` option for the `write_xdlrc` is optional (see [comments for the `parse_args` method](https://github.com/byuccl/tincr/blob/master/tincr/cad/util/util.tcl#L490)). Its default value is the value of Vivado's `general.maxThreads` parameter (see [here](https://github.com/byuccl/tincr/blob/master/tincr/io/device/xdlrc.tcl#L26)). Using `general.maxThreads` ensures that `write_xldrc` is as fast as possible by default, which seems like the desirable behavior to me.
That being said, bug #36 is causing pain for some users whose `general.maxThreads` is set to a value greater than 1. I think the better solution here is to fix that bug rather than change the default to 1.

**Comment by bradselw** [comment]
Closing as won't fix. See bug #36 for progress on the multi-threaded `write_xdlrc` hanging issue.
