### ISSUE TITLE
`tincr::nets list_pips` references non-existent `get_nodes_of_net`

### ISSUE THREAD

**Issue by bradselw** [bradselw/tincr#54]
The command `tincr::nets list_pips` fails with the following  error:
```
invalid command name "get_nodes_of_net"
```

**Comment by mospoly** [comment]
i would be happy to have an answer that solves this problem since this is a very useful command.

**Comment by bradselw** [comment]
This bug has been fixed. Please note that I also updated [README.md](https://github.com/byuccl/tincr/blob/master/README.md) to reflect the correct installation procedure.

**Comment by mospoly** [comment]
Dear @bradselw 

Now this command as well as the add_pip command are working very well, thank you !

Just an issue, the command add_pip is applicable only when we arrive to an input-type PIP in the switch box and then any wire connected to that PIP can be added to the PIP using this command. But you know that some other PIPs in switch box are output-type. While I am trying to connect any wire connected to an output-type PIP, I receive the following error message that clearly says the pip is not accesible since I afraid that we may specify any wire to the output-type PIPs. Look at below, please:

```
tincr::nets::add_pip [get_nets INT_L_X2Y51/BYP_BOUNCE0] [get_pips INT_L_X2Y51/INT_L.BYP_BOUNCE0->>IMUX_L4]
WARNING: [Vivado 12-507] No nets matched 'INT_L_X2Y51/BYP_BOUNCE0'.
ERROR: INT_L_X2Y51/INT_L.BYP_BOUNCE0->>IMUX_L4 is not accessible from .
0
```

Does your tincr tool supports adding a wire to an output-type PIP?

Thanks and Regards,

**Comment by bradselw** [comment]
Hello @mospoly,
Thank you for the great feedback, it is very helpful. Please create a separate issue for tracking this feature request. Also, it would be helpful if you could include a checkpoint from a simple design and/or a script that reproduces the problematic behavior.
